version: "3.9"
services:
  web:
    image: demo_service_bundle
    build: .
    ports:
      - "8000:8000"
    environment:
      - KEYCLOAK_CLIENT_ID=atlas
      - KEYCLOAK_CLIENT_SECRET=<INSERT_YOUR_CLIENT_SECRET_HERE>
